-- LIBRARY SQL CA1
DROP DATABASE IF EXISTS library_CA1;
CREATE DATABASE library_CA1;
USE library_CA1;
	-- JULIETTA

-- CONDITIONS TABLE
-- BOOKS_STATUS TABLE
-- BOOK_COPIES TABLE
-- BOOKS TABLE
-- AUTHORS TABLE
-- PUBLISHERS TABLE
-- SUPPLIERS TABLE

	-- ABOOH

-- LOANS TABLE
CREATE TABLE LOANS();
-- FINES TABLE
CREATE TABLE FINES();
-- WAITLIST TABLE
CREATE TABLE WAITLIST();
-- ROOM_RESERVATIONS TABLE
CREATE TABLE ROOM_RESERVATIONS();
-- ROOMS TABLE
CREATE TABLE ROOMS();
-- CUSTOMERS TABLE
CREATE TABLE CUSTOMERS();
-- BOOK_LOCATION TABLE
CREATE TABLE BOOK_LOCATION();

	-- EESHA

-- STAFF_INFO TABLE
-- STAFF_HR TABLE
-- CONTACTS TABLE
CREATE TABLE ADDRESSES(
	
);
CREATE TABLE DEPARTMENTS(
	
);
-- DEVICE_STATUS TABLE
CREATE TABLE DEVICES(
	
); 
