-- LIBRARY SQL CA1
DROP DATABASE IF EXISTS library_CA1;
CREATE DATABASE library_CA1;
USE library_CA1;
	-- JULIETTA

-- CONDITIONS TABLE
-- BOOKS_STATUS TABLE
-- BOOK_COPIES TABLE
-- BOOKS TABLE
-- AUTHORS TABLE
-- PUBLISHERS TABLE
-- SUPPLIERS TABLE

	-- ABOOH

-- LOANS TABLE
-- FINES TABLE
-- WAITLIST TABLE
-- ROOM_RESERVATIONS TABLE
-- ROOMS TABLE
-- CUSTOMERS TABLE
-- BOOK_LOCATION TABLE

	-- EESHA

-- STAFF_INFO TABLE
-- STAFF_HR TABLE
-- CONTACTS TABLE
-- ADDRESSES TABLE
-- DEPARTMENTS TABLE
-- DEVICE_STATUS TABLE
-- DEVICES TABLE